# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: NucleosMatomoBundle
  description: 📊 This bundle provides a block service for using Matomo inside inside symfony applications.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, matomo, piwik, statistic, sonata, sonata-block

branches:
  - name: main
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Webpack build"
          - "Coding Standards (8)"
          - "Static Code Analysis (8.1)"
          - "Test (PHP 8, symfony 5.4, lowest)"
          - "Test (PHP 8, symfony 5.4, highest)"
          - "Test (PHP 8.1, symfony 5.4, lowest)"
          - "Test (PHP 8.1, symfony 5.4, highest)"
          - "Code Coverage (8.1)"
          - "Mutation Tests (8.1)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
