_extends: .github

repository:
  name: NucleosMatomoBundle
  description: 📊 This bundle provides a block service for using Matomo inside inside symfony applications.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, matomo, piwik, statistic, sonata, sonata-block
